export const ANSI_COLOR_RED = '\x1b[31m'
export const ANSI_COLOR_GREEN = '\x1b[32m'
export const ANSI_COLOR_BLUE = '\x1b[34m'
export const ANSI_COLOR_BOLD = '\x1b[1m'
export const ANSI_COLOR_RESET = '\x1b[0m'
